### ISSUE TITLE
isnull filtering on JSON values doesn't work

### ISSUE THREAD

**Issue by lanzz** [djangonauts/django-pgjson#12]
>>> Model.objects.filter(jsonfield__at_key__isnull=False)
    <repr(<djorm_pgfulltext.models.SearchQuerySet at 0x1119368d0>) failed: django.db.utils.ProgrammingError: operator does not exist: json ->> boolean
    LINE 1: ... "app_model" WHERE ("app_model"."jsonfield"->>'key' ...

I'm expecting this filter to return records that have a non-null value in the `jsonfield->>'key'` field. The generated SQL is however wrong:

    SELECT ... FROM "app_model" WHERE ("app_model"."jsonfield"->>'key' IS NOT NULL)

According to the [PostgreSQL operator precedence table](http://www.postgresql.org/docs/9.3/static/sql-syntax-lexical.html#SQL-PRECEDENCE-TABLE), the `->>` operator has a lower precedence than the `IS` operator, so the above condition is actually parsed as `"jsonfield"->>('key' IS NOT NULL)`, while it should be `("jsonfield"->>'key') IS NOT NULL`.

**Comment by lanzz** [comment]
Apparently other lookup types are also subtly broken:

    Model.objects.filter(jsonfield__at_key__in=['foo', 'bar'])

generates this SQL:

    SELECT ... FROM "app_model" WHERE "app_model"."jsonfield"->>'key' IN ('"foo"', '"bar"')

As you can see, the values being matched are JSON-encoded (there are extra quotes added _within_ the strings), so that condition will match if `jsonfield->>'key'` is `"foo"` (a string of five characters, _including_ the quotes), but will _not_ match if it is just `foo` (a string of three characters).

**Comment by lanzz** [comment]
Two pull requests for both issues described here:
https://github.com/djangonauts/django-pgjson/pull/13
https://github.com/djangonauts/django-pgjson/pull/14

**Comment by niwibe** [comment]
Merged and released 0.2.3 ;) thanks!
