### ISSUE TITLE
How do I order_by by jsonb field?

### ISSUE THREAD

**Issue by scythargon** [djangonauts/django-pgjson#17]

**Comment by pajooh** [comment]
+1

**Comment by niwibe** [comment]
Sincerelly I don't understand why any one would order by and json field. Can you explain more?

**Comment by pajooh** [comment]
in my case, a model has a jsonb field, inside the jsonb, there is a timestamp subfield (last update time), say i want to know the last updated rows, so the only option is order_by, right?

**Comment by 1st** [comment]
@pajooh Hello man. Don't do this. Create `date_update` field in your model and order by this field. The `JSONB` field should be used to store extra information in model, that can contain different key-value pairs (some keys can be in one record, and can be not given in other row).
