### ISSUE TITLE
Issue on setting default value to dict

### ISSUE THREAD

**Issue by gzeronet** [djangonauts/django-pgjson#25]
Hi, I have a model with a json field:

    class CheckJsonDefault(models.Model):
        jb = JsonBField(default={})

and in django command shell:

     In: c1 = CheckJsonDefault.objects.create()
     In: c1.jb == {}
     Out: True
     In: c1.jb['a'] = 'aa'
     In: c1.save()
     In: c2 = CheckJsonDefault.objects.create()
     In: c2.jb == {}
     Out: False   # here is the problem
     In: c2.jb
     Out: {'a': 'aa'}

Seems I can't assign {} or [] as default value for Json(B)Field, it will change default data in new model instance. 
My current solution is set a function (return {}) as default value. 

Please let me know your opinion, and I wish it could be fixed. Thx a lot.

**Comment by niwinz** [comment]
It is already fixed in master. Thanks for report.

**Comment by gzeronet** [comment]
Great, hmm..., maybe deepcopy is safer for multidimensional dict/list. Never mind, thanks.

**Comment by niwinz** [comment]
Hmm, maybe but, is not very common a  have big multidimensional dict on default parameter.
